import type { DadosRiscoItem } from "./etp-riscos";

/**
 * Os 16 riscos-padrão do modelo UERN de Análise de Riscos, genéricos para
 * qualquer contratação (não específicos de um objeto) — usados para
 * pré-carregar uma nova Análise de Riscos, que o Setor Técnico edita,
 * remove ou complementa antes de finalizar.
 */
export const RISCOS_PADRAO: DadosRiscoItem[] = [
  {
    fase: "PLANEJAMENTO",
    descricao: "Ausência da formalização do Documento de Formalização da Demanda (DFD) que origina a contratação",
    danos:
      "Início de processo para contratação que não atende aos normativos legais da Administração Pública, com consequente desperdício de tempo e esforços do requisitante que iniciou o processo",
    probabilidade: "BAIXA",
    impacto: "ALTO",
    nivelAceitacao: "ACEITACAO_INTERMEDIARIA",
    acoesPreventivas: "Elaboração do Documento de Formalização da Demanda (DFD) pelo setor requisitante, antes de iniciar o planejamento da contratação",
    acoesContingenciais: "Autoridade competente não aprova o Termo de Referência (TR)",
    responsavel: "Demandante e Setor Demandante",
  },
  {
    fase: "PLANEJAMENTO",
    descricao: "Contratação sem realização de estudos técnicos preliminares",
    danos: "Contratação que não produz resultados capazes de atender à necessidade da Administração, com consequente não atendimento da necessidade que originou a contratação",
    probabilidade: "BAIXA",
    impacto: "ALTO",
    nivelAceitacao: "ACEITACAO_INTERMEDIARIA",
    acoesPreventivas: "Elaboração do Estudo Técnico Preliminar pela equipe de planejamento / Setor Demandante",
    acoesContingenciais: "Autoridade competente não aprova o Termo de Referência (TR)",
    responsavel: "Setor Demandante",
  },
  {
    fase: "PLANEJAMENTO",
    descricao: "Estudo Técnico Preliminar incompleto, impreciso ou com informações insuficientes",
    danos: "Impossibilidade de se atingir o objetivo esperado total ou parcialmente, com consequente desperdício de recursos",
    probabilidade: "MEDIA",
    impacto: "ALTO",
    nivelAceitacao: "INACEITAVEL",
    acoesPreventivas: "Designação de equipe capacitada tecnicamente para tal",
    acoesContingenciais: "Autoridade competente analisa previamente o ETP",
    responsavel: "Setor Demandante",
  },
  {
    fase: "PLANEJAMENTO",
    descricao: "Mensuração incorreta dos preços estimados pelo demandante",
    danos: "Frustração do planejamento financeiro e orçamentário",
    probabilidade: "BAIXA",
    impacto: "ALTO",
    nivelAceitacao: "ACEITACAO_INTERMEDIARIA",
    acoesPreventivas:
      "Os valores estimados inicialmente são criticados pelo setor de Pesquisa de Preços, utilizando-se das metodologias indicadas pelas normativas legais vigentes",
    acoesContingenciais: "Autoridade competente avalia a necessidade de adequação do Plano de Contratações Anual - PCA",
    responsavel: "Demandante",
  },
  {
    fase: "PLANEJAMENTO",
    descricao: "Mensuração incorreta dos preços cotados",
    danos: "Elevação de custos decorrente do incorreto levantamento dos preços mensurados",
    probabilidade: "BAIXA",
    impacto: "ALTO",
    nivelAceitacao: "ACEITACAO_INTERMEDIARIA",
    acoesPreventivas:
      "Uma vez detectada possível divergência, com base em verificação no portal de compras governamentais e/ou contratações anteriores, nova pesquisa de preços deverá ser realizada para aferição dos valores apresentados",
    acoesContingenciais: "Autoridade competente não aprova o Termo de Referência (TR)",
    responsavel: "Setor de Pesquisa de Preços",
  },
  {
    fase: "PLANEJAMENTO",
    descricao: "Definição de resultados não exequíveis",
    danos: "Frustração do setor demandante e da comunidade acadêmica, com consequente não atendimento da necessidade que gerou a contratação",
    probabilidade: "MEDIA",
    impacto: "ALTO",
    nivelAceitacao: "INACEITAVEL",
    acoesPreventivas:
      "Setor demandante da contratação avalia a possibilidade de a contratação alcançar os resultados esperados definidos pela área requisitante, negociando ajustes quando necessário",
    acoesContingenciais: "Autoridade competente não aprova o Termo de Referência (TR)",
    responsavel: "Demandante e Setor Demandante",
  },
  {
    fase: "PLANEJAMENTO",
    descricao: "Inexistência de análise de risco",
    danos: "Desconsideração dos riscos existentes na contratação e gestão do contrato, com consequente impacto causado por todos os riscos desconsiderados",
    probabilidade: "BAIXA",
    impacto: "ALTO",
    nivelAceitacao: "ACEITACAO_INTERMEDIARIA",
    acoesPreventivas: "Setor demandante da contratação elabora análise de risco da contratação e da gestão contratual",
    acoesContingenciais: "Autoridade competente não aprova o Termo de Referência (TR)",
    responsavel: "Setor Demandante",
  },
  {
    fase: "PLANEJAMENTO",
    descricao: "Termo de Referência (TR) incompleto ou inconsistente",
    danos:
      "TR cujo conteúdo não permite selecionar a proposta mais vantajosa para a Administração ou o contrato sem mecanismos adequados para a gestão contratual, com consequente desperdício de recursos",
    probabilidade: "MEDIA",
    impacto: "ALTO",
    nivelAceitacao: "INACEITAVEL",
    acoesPreventivas:
      "Setor de Planejamento realiza levantamento das falhas verificadas em contratos anteriores junto à gestão e fiscalização contratual, incluindo no TR todos os direitos e deveres de forma clara e objetiva",
    acoesContingenciais: "Autoridade competente não aprova o Termo de Referência (TR)",
    responsavel: "Setor de Planejamento",
  },
  {
    fase: "PLANEJAMENTO",
    descricao: "Questionamentos quanto a exigências contidas no edital, legais e legítimas, mas não usuais",
    danos: "Surgimento de questionamentos no certame (impugnações, recursos), com consequente paralisação do certame até que a exigência seja compreendida ou revista",
    probabilidade: "BAIXA",
    impacto: "MEDIO",
    nivelAceitacao: "ACEITAVEL",
    acoesPreventivas: "Inclusão de referência aos dispositivos legais e/ou jurisprudência que fundamenta as exigências não usuais",
    acoesContingenciais: "Pregoeiro e equipe de planejamento dão celeridade aos questionamentos e revisam as exigências quando necessário",
    responsavel: "Setor de Planejamento / Agente de Contratação",
  },
  {
    fase: "SELECAO_FORNECEDOR",
    descricao: "Empresas sem qualificação e/ou não habilitadas participando da licitação",
    danos: "Contratação de empresa incapaz de executar o contrato, com consequente não obtenção do objeto contratado e descumprimento das obrigações previstas",
    probabilidade: "MEDIA",
    impacto: "ALTO",
    nivelAceitacao: "INACEITAVEL",
    acoesPreventivas: "Agente de Contratação inclui no edital exigências de habilitação jurídica, fiscal, econômico-financeira e técnica",
    acoesContingenciais: "Autoridade competente, ao verificar que o adjudicado não comprovou as exigências, não homologa e remete o processo ao Agente de Contratação",
    responsavel: "Agente de Contratação / PROAD",
  },
  {
    fase: "SELECAO_FORNECEDOR",
    descricao: "Não consultar todas as listas onde constam restrições para contratar com a Administração Pública",
    danos: "Contratar licitante com restrições, com consequente descumprimento da legislação, incluindo a possibilidade de ilícito penal",
    probabilidade: "BAIXA",
    impacto: "ALTO",
    nivelAceitacao: "ACEITACAO_INTERMEDIARIA",
    acoesPreventivas: "Consultar, na etapa de julgamento, as listas elaboradas pelos Órgãos Governantes Superiores",
    acoesContingenciais: "Autoridade competente, ao verificar restrição não comprovada, não homologa e remete o processo ao Agente de Contratação",
    responsavel: "Agente de Contratação / PROAD",
  },
  {
    fase: "SELECAO_FORNECEDOR",
    descricao: "Ausência de clareza sobre data e hora dos eventos relacionados ao pregão eletrônico",
    danos: "Impedimento de os licitantes praticarem atos no certame licitatório, com consequente afronta aos princípios da publicidade, transparência e isonomia",
    probabilidade: "BAIXA",
    impacto: "ALTO",
    nivelAceitacao: "ACEITACAO_INTERMEDIARIA",
    acoesPreventivas: "Agente de Contratação divulga com clareza no sistema eletrônico as informações relativas à data e hora das sessões públicas",
    acoesContingenciais: "Ao perceber a falta de clareza, informa nova data com antecedência mínima de 24 horas",
    responsavel: "Agente de Contratação",
  },
  {
    fase: "SELECAO_FORNECEDOR",
    descricao: "Licitação fracassada ou deserta",
    danos: "Demora no processo de contratação, gerando prejuízos ao andamento das atividades da Administração",
    probabilidade: "MEDIA",
    impacto: "ALTO",
    nivelAceitacao: "ACEITACAO_INTERMEDIARIA",
    acoesPreventivas: "Inclusão de pré-requisitos dos licitantes e características dos serviços essenciais ao objeto da licitação",
    acoesContingenciais: "Repetição da licitação com a devida revisão dos motivos que originaram o seu fracasso",
    responsavel: "Demandante / Agente de Contratação / PROAD",
  },
  {
    fase: "GESTAO_CONTRATO",
    descricao: "Ausência de acompanhamento e fiscalização da execução do contrato",
    danos: "Ocorrência de distorções na prestação de serviços e/ou utilização de materiais em desacordo com o licitado",
    probabilidade: "BAIXA",
    impacto: "ALTO",
    nivelAceitacao: "INACEITAVEL",
    acoesPreventivas: "Setor demandante inclui no TR a previsão de acompanhamento e fiscalização do contrato, por gestores contratuais especificamente designados",
    acoesContingenciais: "Autoridade competente capacita gestores e fiscais para uma fiscalização mais efetiva",
    responsavel: "Demandante / PROAD",
  },
  {
    fase: "GESTAO_CONTRATO",
    descricao: "Os gestores e fiscais dos contratos atuam sem nomeação formal",
    danos: "Questionamento da legitimidade dos atos praticados na gestão contratual, com consequente impossibilidade de responsabilizar as partes",
    probabilidade: "BAIXA",
    impacto: "ALTO",
    nivelAceitacao: "INACEITAVEL",
    acoesPreventivas: "Autoridade competente nomeia previamente ao início da execução contratual os representantes e seus substitutos eventuais",
    acoesContingenciais: "Autoridade competente identifica os gestores e fiscais atuando sem portaria e emite o documento imediatamente",
    responsavel: "PROAD",
  },
  {
    fase: "GESTAO_CONTRATO",
    descricao: "Serviços prestados de maneira diversa da prevista no contrato",
    danos: "Erro na execução do serviço, serviços ineficientes ou precários, frustração do setor demandante, dano ao erário",
    probabilidade: "MEDIA",
    impacto: "ALTO",
    nivelAceitacao: "INACEITAVEL",
    acoesPreventivas: "Setor demandante inclui no TR as diretrizes que nortearão a prestação dos serviços, verificadas pelos gestores e fiscais",
    acoesContingenciais: "Equipe de gestores e fiscais do contrato fiscaliza constantemente os serviços, verificando o atendimento de todos os termos contratuais",
    responsavel: "Demandante / PROAD",
  },
];
